### ISSUE TITLE
終了報告

### ISSUE THREAD

**Issue by Taka41802** [Taka41802/furima-41802#11]
# 概要
FURIMAの実装が完了したことを報告する

# 提出までの流れ
- 本番環境で、すべての機能が実装条件通りに動くことを確認する。
- 本番環境のデータベースをリセットする。
- 本番環境で新たにユーザーを作成する。
- 終了報告フォームを提出する。

# 提出条件
- [x] すべてのプルリクエストに対して、LGTMが出ていること。
- [x] 本番環境で、すべての機能が実装条件通りに動いていること。
- [x] 本番環境のデータベースをリセットした上で、ユーザーを再度作成していること。

# 注意事項
- 参考カリキュラムをよく読み、終了報告を行うこと。

# 参考カリキュラム
- 終了報告の提出
最終課題カリキュラム Lesson2 「最終課題を提出しよう」

**Comment by Taka41802** [comment]
#URL

https://furima-41802.onrender.com/

お願いします。

**Comment by motomuun** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**

- [x] **販売手数料と販売利益の合計が、販売価格と一致すること**
手数料と利益の合計が、価格と一致していません。一致するように修正しましょう。
<img width="657" alt="スクリーンショット 2024-12-13 9 30 50" src="https://github.com/user-attachments/assets/6175edf4-5ba6-4bc1-939e-abd142a2d301" />

**商品購入機能の確認**

- [x] **クレジットカード情報は必須であり、PAY.JPテストカードの情報で決済ができること**
クレジットカード情報入力フォームのカーソルを合わせても、入力が出来ません。入力できるように修正しましょう。

- [x] **配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であること**
都道府県が入力されていなくてもエラーメッセージが表示されません。都道府県が必須項目となり、入力されていない場合はエラーメッセージが表示されるように修正しましょう。

※購入後の挙動に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Taka41802** [comment]
変更しました！

https://furima-41802.onrender.com

**Comment by motomuun** [comment]
最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
